### PR TITLE
Better style

### PR DESCRIPTION
**Pull request by eVanilla**
Is everything all right asking?
Well. Almost 1 month ago I made a request and nobody cared for it, and I decided to do it myself.
And I know it's a little work, but I wanted to show you guys that I also have other ideas for improving ui & stuff.

### CODE REVIEW

**Comment by Flaburgan** [comment]
Sorry I wanted to check your PR but my dev env is currently broken. I'll try to have a look in the coming days.

**Comment by Flaburgan** [comment]
So, I finally succeed to run the official website locally, to try your PR.
It looks like that:
screenshot-2018-3-31 le projet diaspora

So it looks like you have changed:
- The header background, going from black to white
- The "hero" background, replacing the grey by a gradient
- The background of the page, from white to grey, adding some box around the text, with white background and shadow.

That's what I spotted with a very quick look. Did I miss something?

My first feedback would be partially negative unfortunately. I don't think we should do the 2 first changes I listed mainly for the following reason: we're trying to keep a common identity between the official website and diaspora* itself. The colors are well defined: the header is black, the buttons are blue or green, etc. From that point of view, a white header followed by a purple hero isn't what we want in my opinion.

However, your last change is interesting: the background which was white in diaspora* has been changed to grey with the content put in white box, exactly like you did here. The website hasn't been updated with that change, so maybe we want to do it. I'll wait for others' opinion on that point before giving you a go, but that change can be a good one.

In any case, thank you for helping improve diaspora* and sorry again for the very late answer.

**Comment by Flaburgan** [comment]
I actually tried the grey background for the footer in https://github.com/diaspora/diaspora-project-site/pull/119. It feels better that way imo, more unified with diaspora*.

**Comment by SuperTux88** [comment]
> From that point of view, a white header followed by a purple hero isn't what we want in my opinion.

I agree with that, also I think it shouldn't be that big (it covers almost half of the page) ... on every page, so you need to scroll on some pages now, where you didn't need to scroll before:

image

before:

image

**Comment by Flaburgan** [comment]
@eVanilla #119 has been merged so the footer is now unified, as you proposed. I can still be interested by the changes from white to grey background with white shadowed boxes for content, I'm not sure (maybe at least not in the home page, I plan to change its content).

**Comment by denschub** [comment]
This PR got automatically closed by GitHub after we deleted the `master` branch and replaced the default branch with `production`. I did miss that this change will close all open PRs, sorry for that. Since there has been no activity for a while, I think this is fine, but if someone feels strongly about this, please let me know and we can restore this. :)

**Pull request closed without merging**
