### PR TITLE
Add community statement

### PR DESCRIPTION
**Pull request by svbergerem**
In the first commit I added the original statement. In the second commit I changed the text a bit.

There is currently no link to this page but once this page is online we can publish a blog post with a link and add the link to the diaspora sidebar.

diaspora community statement

### CODE REVIEW

**Comment by goobertron** [comment]
Thanks for doing this. I'm perhaps coming a bit late to this - I forgot about it after the vote was passed - but I wanted to look at the language and make some amendments. I've just done these in a branch on my own repo. I'll post a link here: https://github.com/goobertron/diaspora-project-site/commit/897e80755867f3f3455e1c2891d0670e4e572a84

The changes are:

- using 'person' instead of 'creature'. I think using 'person' helps embed the idea of respect into the statement, and diaspora doesn't offer anything to any non-persons (i.e. non-human creatures).
- moving the diaspora ideals into a third paragraph, after the phrase that states that diaspora needs considerate interaction based on diaspora's ideals.
– adding 'our motto' in front of the motto, for emphasis.
- various other changes which I think improve the text.

All of these are mere preference. A few are based on being a native English-speaker and my experience editing English prose. Others are more a matter of personal judgement. E.g. I think saying 'level of ability or disability' instead of simply 'disability' helps as all other considerations in that sentence are terms which suggest a spectrum, for instance 'age' instead of 'being old'. However, others might consider that weighing 'ability' against 'disability' might be undesirable for political reasons. It might be worth discussing some of these things. If others feel any of these suggestions are not improvements, I am of course happy for them to be rejected,

Perhaps the best thing to do would be to merge this PR once approved, whether or not any of my suggestions are included, but not link to the  page from anywhere, and then ask the community what they think.

**Comment by cmrd-senya** [comment]
I have no personal opposition for the text, but if it is stated from the community side, should it be agreed with the community using Loomio first?

**Comment by goobertron** [comment]
Senya, see [the Loomio vote](https://www.loomio.org/d/F5zxTwiX/proposal/MUv9Yy3d).

**Comment by cmrd-senya** [comment]
Ah, it's fine. I voted there myself. I remember the voting, but I thought that the statement from this PR is something new and different from what was discussed there. Sorry for the fuss!

**Comment by goobertron** [comment]
There are no substantive changes; it's mostly a matter of semantics and polishing the language. I tend to find Loomio is a bit messy for fine-tuning things.

**Comment by svbergerem** [comment]
@goobertron Thanks a lot for your suggestions! It would be much easier to just comment on your commit, but I'd like to keep the discussion in one place.

```diff
- all kind of creatures
+ every kind of person
```
I think the word “creatures” is derived from a [statement of the Chaos Computer Club](https://www.ccc.de/en/updates/2016/a-reminder-to-be-excellent-to-each-other):

> The CCC is, by its charter and by common consent, a **galactic organization of all life forms**. We are dedicated to providing a safe, comfortable, and supportive experience for everybody attending our events.
> [...]
> **All creatures are welcome**: CCC events aim to create a safe space for all attendees, regardless of their age, race, gender, sexual orientation, physical appearance or disability, choice of text editor, or any other qualities by which living beings can be discriminated.

On diaspora\* it doesn't matter if you are a person, unicorn, cat, flower, troll or any other life form / creature. I get your point, but I still like the idea of supporting all life forms / creatures.

 ```diff
- disability
+ level of ability or disability
```
That part is just copied from our [code of conduct](https://github.com/diaspora/diaspora/blob/develop/CODE_OF_CONDUCT.md#our-pledge). I'm not a native speaker and can't add anything else to the discussion, so that's all I'll say about it.

```diff
- To give all of us the best possible time on diaspora*, we envision a respectful interaction.
+ To help all of us to have the best possible experience on diaspora*, we envision a community which interacts respectfully.
```
👍 

Moving things to a new paragraph: 
👍 

```diff
- Ever more important for diaspora* to live on is a considerate interaction based on the ideals of the diaspora*-community.
+ Considerate interaction based on the ideals of the diaspora* community is therefore crucial to the wellbeing of this network.
```
👍 

```diff
- <strong>Stay calm, and be excellent to each other.</strong>
+ Our motto: “<strong>Stay calm, and be excellent to each other!</strong>”
```
I prefer the first version (+ the exclamation mark). The sentence is already emphasized by the `<strong>` tags and in the first version it looks “unfussier”. (I looked that word up, not sure if it's correct in this context)

Various “how to changes”:
👍

**Comment by goobertron** [comment]
Thanks for your reply, @svbergerem. If there's a reason for things being the way they are, then of course they should stay that way. So:
- the word “creatures” is derived from a statement of the Chaos Computer Club
- That part is just copied from our code of conduct.
We should keep those as they are.

I take your point about 'creatures' referring to the way someone presents themselves on diaspora. I hadn't thought about that, and in that context 'creatures' certainly makes sense. It is grammatically correct to say either 'all kinds of creature' (plural 'kinds', singular 'creature') or 'every kind of creature' (both singular). The latter is better. Would you be happy with that? I see the CCC statement just refers to 'creatures' rather than 'all kind of creatures' so this wouldn't make any change to their original statement.

Thanks again for all your work.

**Comment by svbergerem** [comment]
@goobertron 
> every kind of creature

Sounds good. There is a new commit also containing the other suggested changes.

**Comment by svbergerem** [comment]
I talked to @denschub and @SuperTux88 about the headline. Here is, what we came up with:

community guidelines screenshot

**Comment by goobertron** [comment]
I'm not sure the byline quite fits what the text actually is: a statement of wish, a desire. 'Rules' sounds as though this is something which is being imposed from the top down, and in any case this can't be enforced, except by podmins, who will decide and implement their own terms of use. How about '**Guidelines for being part of diaspora\*'s community**' for the byline? Alternatively, '**How to be a valued member of diaspora\*'s community**'.

Also, we should use sentence case for the English version, as is used across diaspora's UI. This applies to the menu [page] title as well as the headings.

Thanks again!

**Comment by Flaburgan** [comment]
What about only one title: "Social Principles & Community Guidelines"?

**Comment by svbergerem** [comment]
@denschub Should be fixed now.

community guidelines final

**Comment by denschub** [comment]
Let's do it!

**Pull request merged**
