### PR TITLE
Adding sq translation to site

### PR DESCRIPTION
**Pull request by ujdhesa**
Hello,

I’ve finished the translation of the bits requested to display the foundation site in Albanian. Please pull them into master.

### CODE REVIEW

**Comment by ujdhesa** [comment]
I need to check that translation on WTI. I thought nobody has started there with the site strings.

**Comment by ujdhesa** [comment]
@jhass https://webtranslateit.com/en/projects/7017-Website/locales/en..sq/strings doesn't show any previous attempt to translate. So there's no conflict of that kind.

Please let me know when the translation makes into production, so I can have a last look for any slipped error.

**Comment by jhass** [comment]
Oh my bad then, looks like I was looking at the wrong place.

**Comment by ujdhesa** [comment]
Translation moved to that external translation service. This pull request is no longer needed. Please close it.

**Pull request closed without merging**
