### PR TITLE
Better explanation of privacy and who can access your data

### PR DESCRIPTION
**Pull request by goobertron**
To address the concerns in #86.

I think it's enough, but if anyone feels more clarity is needed or the text is still misleading, please say so.

### CODE REVIEW

**Comment by denschub** [comment]
> 614 additions, 550 deletions not shown because the diff is too large. Please use a local Git client to view these changes. 

Thanks, goob.

**Comment by denschub** [comment]
Oh wait, you actually were not that astonishingly assiduous, you actually made mass changes. Why is it you've replaced all double quotes with single quotes? Looks a bit superfluous to me!

**Comment by goobertron** [comment]
Yeh, that was me. I thought it was a good idea to introduce consistency. Is that not wanted?

I am actually surprised to see those listed as changes in the diff on this commit as I made them in a commit which has already been merged (https://github.com/diaspora/diaspora-project-site/commit/a47d43ba17d29f615355f37c6d6ca0dc1833fa6e). This was the one in which I mistakenly deleted the header line for the formatting page, which broke all the translations for that page. The double quotes must have been reintroduced when you fixed that. That's weird, because the other changes I made to that file seem to appear on the live site.

What best to do? Let me know if you need me to revert the quote marks. That might be a bit of work as I'll have to then extract all the changes I've made to the tutorials for v0.6.

**Comment by denschub** [comment]
Nah.

First, if you want to make mass changes, do them in a separate PR. This mix of content changes and mass changes make this PR almost impossible to review. Also, we usually do use double quotes everywhere, and that's what webtranslateit generates for us. Sorry, I cannot merge this.

I'll replace the quotes with some editor magic soonish. But please don't do that in future PRs.

**Comment by goobertron** [comment]
As said, the standardisation of quote marks was done in a previous PR, which has already been merged. I can't answer why the mixed quote marks have appeared in `master` again, but when I created this branch and pushed it, the standardised single quotes were there.

This PR only makes a change to one or two strings, so I'll redo it quickly now.

**Comment by goobertron** [comment]
@denschub  done! Hope that's all right now.

**Comment by denschub** [comment]
> As said, the standardisation of quote marks was done in a previous PR

Yeah, Jonne merged that without too much attention. That's fixed now, so everything is allright. :)

> I can't answer why the mixed quote marks have appeared in `master` again

When Jonne merged the PR with your broken translations, he pushed it to webtranslateit. Since you killed one subsection, WTI also removed that strings and all translations. I had to force-push a fixed revision back to WTI to get the translations back, and pulled the new, fixed, translations back down, which is why the quotes were rewritten by wti.

Your PR is merged. Thanks much.

**Comment by goobertron** [comment]
Ah, right. Thanks for explaining. As usual, it is *all my fault*. [blush icon]

Thanks for helping me get it fixed! <3

**Pull request merged**
