### PR TITLE
Reword 'Choose a pod', add a link to the wiki installation page

### LINKED ISSUE #78: Error on page https://diasporafoundation.org
On the page https://diasporafoundation.org (in french), the link toward pods list is missing :
"Une liste des pods de la communauté est disponible ici %{poduptime}."

### PR DESCRIPTION
**Pull request by Flaburgan**
Close #78

### CODE REVIEW

**Comment by goobertron** [comment]
Typo: 'conneciton' -> 'connection'.

I'd like to reword this slightly, if you don't mind:

> choose_pod_exp: "Find a pod that suits you. You might prefer a smaller pod, one which is allows cross-posting to external services (such as Twitter), one based near you, or one based in a country that you know has good data security policies... The choice is yours! You can even %{host_yourself_link} if you have some sysadmin skills."
>      host_yourself: "host a pod yourself"

**Comment by Flaburgan** [comment]
Thanks for your review Goob, I applied your suggested changes.

**Comment by Flaburgan** [comment]
Up? :)

**Comment by denschub** [comment]
Merged, thanks! ❤️

**Pull request merged**
