### PR TITLE
Repair all broken strings in UI

### PR DESCRIPTION
**Pull request by goobertron**
This fixes https://github.com/diaspora/diaspora-project-site/issues/89 and https://github.com/diaspora/diaspora-project-site/issues/91.

@Flaburgan, please would you pull this into your local installation and check that I haven't missed anything? You could compare with https://github.com/goobertron/diaspora-project-site/commit/beafa22721f155442bc2f9563cce5c9cfe9a4acd to make sure I haven't done anything silly. I've checked myself, and I'm fairly sure that everything is as it should be, but my concentration isn't 100% at the moment so I'd really appreciate your eyes over this.

### CODE REVIEW

**Comment by denschub** [comment]
❤️

**Comment by Flaburgan** [comment]
Thank you **very much** for doing that. I'm going to review it on Friday midday.

**Comment by Flaburgan** [comment]
You missed
>Top Buttons
Top Buttons Ex1
    Top Buttons List1
    Top Buttons List2
    Top Buttons List3
    Top Buttons List4
    Top Buttons List5
    Top Buttons List6
    Top Buttons List7
    Top Buttons List8
    Top Buttons List9

On the `getting_started/sharing` page.

**Comment by goobertron** [comment]
Whoops! Thank you for spotting that. How did I miss such a big mistake? Anyway, all are there now. Revise commit now pushed. Thanks for reviewing it carefully!

**Comment by Flaburgan** [comment]
@denschub if you have some time to merge this and push to prod it would be awesome <3

**Comment by denschub** [comment]
Done!

**Pull request merged**
